spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:your-very-long-secret-key-at-least-64-characters-long-1234567890abcdefghijklmnopqrstuvwxyz}
  expiration: ${JWT_EXPIRATION:86400000} # 24 часа