spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibarnate:
        format_sql: true